### ISSUE TITLE
Bug "read .: is a directory"

### ISSUE THREAD

**Issue by Draikon** [MalteBoehm/repo-copy#1]
When executing the repo-copy command on macos in the root folder of an git project the following message occurs:

"read .: is a directory"

No further processing is done by the cli.

**Comment by MalteBoehm** [comment]
Hey there, is it just the unexpected message or is it also not working? I run it myself on MacOS.

**Comment by MalteBoehm** [comment]
Should be resolved now. My mistake was that I returned an error when it's a non-binary instead of a nil.
